# -- Allgemein ---------------------------------------------------------------------------------------------------------
quarkus.http.auth.basic=true

quarkus.log.level=INFO
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=update
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=wildtierrettung


# -- Produktion ---------------------------------------------------------------------------------------------------------
# -- Dev ---------------------------------------------------------------------------------------------------------
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=importiereTestDaten.sql
%dev.quarkus.hibernate-orm.log.sql=true

